name: cerbere_admin
description: Flutter admin package for roles and permissions with Firebase. Companion to cerbere; requires Firebase Admin SDK for user management.
version: 0.1.0+2

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  cerbere: ^0.1.0
  cloud_firestore: ^6.0.0
  dart_firebase_admin: ^0.4.1
  equatable: ^2.0.0
  firebase_auth: ^6.0.0
  flutter_bloc: ^9.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

homepage: https://github.com/Sushy974/cerbere_admin
repository: https://github.com/Sushy974/cerbere_admin
issue_tracker: https://github.com/Sushy974/cerbere_admin/issues
documentation: https://github.com/Sushy974/cerbere_admin#readme
topics:
  - firebase
  - admin
  - roles
  - permissions
  - flutter

screenshots:
  - description: "Logo et identité visuelle du package Cerbère Admin."
    path: assets/images/cerbere_admin.png
